/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreclientRouteImport } from './routes/preclient'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor/index'
import { Route as AdvisorApplicationIdRouteImport } from './routes/advisor/$applicationId'

const PreclientRoute = PreclientRouteImport.update({
  id: '/preclient',
  path: '/preclient',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/advisor/',
  path: '/advisor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorApplicationIdRoute = AdvisorApplicationIdRouteImport.update({
  id: '/advisor/$applicationId',
  path: '/advisor/$applicationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preclient': typeof PreclientRoute
  '/advisor/$applicationId': typeof AdvisorApplicationIdRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preclient': typeof PreclientRoute
  '/advisor/$applicationId': typeof AdvisorApplicationIdRoute
  '/advisor': typeof AdvisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preclient': typeof PreclientRoute
  '/advisor/$applicationId': typeof AdvisorApplicationIdRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preclient' | '/advisor/$applicationId' | '/advisor/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preclient' | '/advisor/$applicationId' | '/advisor'
  id: '__root__' | '/' | '/preclient' | '/advisor/$applicationId' | '/advisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreclientRoute: typeof PreclientRoute
  AdvisorApplicationIdRoute: typeof AdvisorApplicationIdRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preclient': {
      id: '/preclient'
      path: '/preclient'
      fullPath: '/preclient'
      preLoaderRoute: typeof PreclientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/advisor'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/$applicationId': {
      id: '/advisor/$applicationId'
      path: '/advisor/$applicationId'
      fullPath: '/advisor/$applicationId'
      preLoaderRoute: typeof AdvisorApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreclientRoute: PreclientRoute,
  AdvisorApplicationIdRoute: AdvisorApplicationIdRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
